# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

command_timeout = 950

# Use custom format
format = '''
[┌─────────┤ ](bold green)$directory$git_branch$git_metrics$git_status$rust$golang$lua$package
[└─⎨](bold green) '''

right_format = """$git_commit"""

[c]
symbol = " "

[directory]
truncation_length = 5
truncation_symbol = "  "
truncate_to_repo = false
style = "#CEDBE8"
repo_root_style = "bold #1E90FF"
format = "[$path]($style)[$lock_symbol]($lock_style) "
read_only = " "

[docker_context]
symbol = " "

[git_branch]
symbol = " "
style = "bold #3FA75C"

[git_commit]
commit_hash_length = 7
only_detached = false
format = "[$hash]($style) "
style = "#BDCAD7"

[git_metrics]
disabled = false

[git_status]
style = "fg:#BDCAD7"
stashed = " ${count}"
ahead = '( [ﲗ\($count\)](bold #C6D0D8))'
behind = '( [ﲔ\($count\)](bold #C6D0D8))'
diverged = "李 ${ahead_count} ${behind_count}"
conflicted = '( [\($count\)](bold #C6D0D8))'
deleted = '( [\($count\)](bold #C6D0D8))'
renamed = '( [﫦\($count\)](bold #C6D0D8))'
modified = '( [M\($count\)](bold yellow))'
staged = '( [S\($count\)](bold green))'
untracked = '( [\($count\)](red))'
format = "$all_status$ahead_behind "

[golang]
symbol = " "
format = '[$symbol]($style)'

[julia]
symbol = " "

[lua]
symbol = " "
format = '[$symbol]($style)'

[memory_usage]
symbol = " "

[nodejs]
symbol = " "
format = '[$symbol]($style)'

[package]
symbol = " "
disabled = true

[python]
symbol = " "

[rust]
symbol = " "
format = '[$symbol]($style)'
